# Generated by Django 4.2.2 on 2023-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_timer_start_time_alter_timer_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='remaining_time',
            field=models.IntegerField(null=True),
        ),
    ]
